version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 */14 * *"
      timezone: "UTC"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 7 8-31/14 * *"
      timezone: "UTC"
    open-pull-requests-limit: 1
    groups:
      gomod:
        patterns:
          - "*"
